name: sample-workflow
reference: vulnshot.com/sample/blog/post
description: Subdomain Enumeration, Vulnerability Scanning, and Notification
pipeline:
  - name: subfinder
    cat_base: subdomain # category base of tools / pipeline name, can leave blank, or put whatever you want
    output_file: # you can add prefix output file name or leave blank (default: result will be saved in result-scan/{cat_base}/{pipeline_name}/{domain})
    command: |
      subfinder -silent -d {domain} | anew {output_file} &&
      echo {domain} >> {output_file}

  - name: assetfinder
    cat_base: subdomain # category base of tools / pipeline name, can leave blank, or put whatever you want
    output_file: # you can add prefix output file name or leave blank (default: result will be saved in result-scan/{cat_base}/{pipeline_name}/{domain})
    command:  assetfinder --subs-only {domain} | anew {output_file}

  - name: dnsgen
    cat_base: subdomain # category base of tools / pipeline name, can leave blank, or put whatever you want
    output_file: # you can add prefix output file name or leave blank (default: result will be saved in result-scan/{cat_base}/{pipeline_name}/{domain})
    command: echo {domain} | dnsgen - | anew {output_file}

  - name: nuclei
    cat_base: vuln-scanner # category base of tools / pipeline name, can leave blank, or put whatever you want
    output_file: # you can add prefix output file name or leave blank (default: result will be saved in result-scan/{cat_base}/{pipeline_name}/{domain})
    command: cat subfinder.output_file | nuclei -tags git -silent -nc | anew {output_file}

  - name: notify  
    cat_base: # category base of tools / pipeline name, can leave blank, or put whatever you want
    command: |
      cat nuclei.output_file| notify -silent -bulk  