name: subdo-enum-wf
reference: vulnshot.com
pipeline:
  - name: subfinder
    cat_base: subdomain
    output_file:
    command: |
      subfinder -silent -d {domain} -o {output_file} &&
      echo {domain} >> {output_file}

  - name: yusub
    cat_base: subdomain
    output_file:
    command: yusub {domain} | tee -a {output_file}

  - name: dnsgen
    cat_base: subdomain
    output_file:
    command: sort -u subfinder.output_file yusub.output_file | dnsgen - | tee -a {output_file}

  - name: httprobe
    cat_base: subdomain
    output_file: live
    command: |
      sort -u subfinder.output_file yusub.output_file dnsgen.output_file | httprobe -prefer-https -c 50 -silent | tee {output_file}

  - name: subdosec
    cat_base: subdomain
    output_file:
    command: |
      cat httprobe.output_file | subdosec -vo -mode private -su | tee -a {output_file}

  - name: nuclei
    cat_base: vuln-scanner
    output_file:
    command: cat httprobe.output_file | nuclei nuclei -nh -as -itags js,seclist,passive,network,file,fuzz,headless,extractor,tech,dns,code,linux,privesc,cloud,devops,osint,tcp,kev,exposure -silent -o {output_file}

